[Appearance]
color_scheme_path=~/.config/qt5ct/colors/matugen.conf
custom_palette=true

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x2g\0\0\x2\x9f\0\0\0\0\0\0\0\0\0\0\x2u\0\0\x2\xa8\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x2g\0\0\x2\x9f)
