# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Set prifix to CTRL + SPACE
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix


# Mouse On
set -g mouse on


# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


# Create Panes&Windows
bind n split-window -h -c "#{pane_current_path}"
bind e split-window -v -c "#{pane_current_path}"
bind a confirm-before -p "kill-window? (y/n)" kill-window
bind r confirm-before -p "kill-pane? (y/n)" kill-pane


# Theming
source-file ~/.config/tmux/generated.conf

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
